# reference: https://www.gitpod.io/docs/references/gitpod-yml
# image: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .devcontainer/Dockerfile
tasks:
  - name: repo
    # before: |
    #   nvm install
    before: |
      node -v
      npm -v
      poetry env info
      go version
    init: |
      npm install
      gp sync-done repo
  - name: ts
    before: |
      cd ts
      gp sync-await repo
      # nvm use
    init: |
      npm install
      npm run build
    openMode: tab-after
  - name: py
    before: |
      cd py
      gp sync-await repo
      # pyenv install --force
      # pyenv local 3.9.16
      # poetry env use $(pyenv which python)
    init: |
      poetry install
      poetry build
    openMode: tab-after
  - name: go
    before: |
      cd go
      gp sync-await repo
    init: |
      go install
    openMode: tab-after
ports:
  # todo: uncomment when docs are migrated from configu.com/docs to this repo
  # - name: Docs
  #   port: 3000
  #   onOpen: open-preview
  - name: React Example
    port: 8080-8100
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
