name: "CI: release drafter"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update release draft
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ts, py, go, lib, cli, vscode]
    steps:
      - uses: actions/checkout@v4

      - name: Draft release config
        run: |
          cat .github/configs/release-drafter.yml >> .github/configs/${{ matrix.package }}-release-drafter.yml
          cat .github/configs/${{ matrix.package }}-release-drafter.yml

      - name: Draft release ${{ matrix.package }}
        uses: release-drafter/release-drafter@v5
        with:
          config-name: configs/${{ matrix.package }}-release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
